namespace Ago.Chat.Domain;

/// <summary>
/// `26-03`/`adr/0179` §1: one row per (operator, app installation) - never per token, which is the
/// single decision that makes FCM token rotation work at all. A small aggregate root of exactly one
/// entity, in the shape <see cref="WebhookEndpoint"/> already has.
///
/// <para><b>Why this is a Domain type and not a bare row in Infrastructure.</b> It owns two real rules
/// that must not live in a handler: <see cref="Token"/> has a bounded length and may not be blank (the
/// same bounded-value discipline <see cref="MessageBody"/> and
/// <see cref="ChannelDelivery.MaxProviderDetailLength"/> apply), and a revoked device sends nothing
/// until a fresh registration revives it. The alternative - a nullable column a query happens to
/// filter on - puts that second rule in every caller's `WHERE` clause, and it drifts the first time
/// somebody writes a second query. It is deliberately *not* a type with children or a state machine:
/// there are exactly two mutations, <see cref="Refresh"/> and <see cref="Revoke"/>, and `adr/0179`
/// calls both of them idempotent - stated once here rather than at each call site.</para>
///
/// <para><b>Identity is `(OperatorId, InstallationId)`, checked by `OperatorDeviceConfiguration`'s own
/// unique index, never by this type</b> - the same "the index is the backstop, the write path is the
/// real mechanism" split `ChannelIdentityConfiguration`'s own remarks describe: nothing in this
/// aggregate can see a sibling row, so the uniqueness of the pair is a storage-level fact, not a
/// Domain invariant this type could ever check for itself.</para>
///
/// <para><b>A device belongs to an <see cref="Operator"/>, not to a bare Keycloak identity</b> -
/// `operators` is itself uniquely indexed on `(external_subject_id, site_id)`, and one person may hold
/// several tenancies. The fan-out events this table exists to serve
/// (`Ago.Chat.Contracts.ConversationAssignedToOperator`) already name an <see cref="Domain.OperatorId"/>,
/// so keying here on anything else would add a lookup to reach the same answer, and would risk a
/// notification about one tenant reaching a device registered while the operator worked for another
/// (`tenant-isolation.md`).</para>
/// </summary>
public sealed class OperatorDevice
{
    /// <summary>Generous rather than tight - no provider's registration token format is pinned by any
    /// spec this system depends on, and a bound exists only so one row can never become an unbounded
    /// write, the identical reasoning <see cref="MessageBody.MaxLength"/> states for itself.</summary>
    public const int MaxTokenLength = 4096;

    /// <summary>The client-generated identifier is expected to be a UUID or similarly short opaque
    /// string; bounded for the same reason <see cref="MaxTokenLength"/> is, not because anything
    /// observed needs more.</summary>
    public const int MaxInstallationIdLength = 256;

    public const int MaxPlatformLength = 32;

    public OperatorDeviceId Id { get; }

    public SiteId SiteId { get; }

    public OperatorId OperatorId { get; }

    /// <summary>Client-generated, stable for the life of one app install - this, with
    /// <see cref="OperatorId"/>, is the row's identity (`OperatorDeviceConfiguration`'s own unique
    /// index). Never regenerated by <see cref="Refresh"/>.</summary>
    public string InstallationId { get; } = string.Empty;

    public PushProvider Provider { get; private set; }

    /// <summary>`'android'` today - diagnostic only, the same "not part of any lookup key" role
    /// <see cref="ExternalChannelAddress"/>'s own channel-neutral remarks give for data that describes
    /// a row rather than identifies it.</summary>
    public string Platform { get; private set; } = string.Empty;

    /// <summary>The provider's own registration token - a value <em>on</em> this row, replaced in place
    /// by <see cref="Refresh"/> on every rotation, never a second row. This is the whole of the
    /// token-rotation story (`adr/0179` §1): a table keyed on the token instead would accumulate one
    /// dead row per rotation forever.</summary>
    public string Token { get; private set; } = string.Empty;

    public DateTimeOffset CreatedAt { get; }

    /// <summary>Rewritten on every <see cref="Refresh"/> - what a future operational query sorts by to
    /// find a dead install, once `26-04`/`26-05` exist to run one.</summary>
    public DateTimeOffset LastSeenAt { get; private set; }

    /// <summary><see langword="null"/> for a live device. Set by sign-out, by the provider reporting the
    /// token gone, or by `OperatorRemovedConsumer`'s own added call - never by a timer (`adr/0179`: "a
    /// phone in a drawer for three weeks is not a revoked device").</summary>
    public DateTimeOffset? RevokedAt { get; private set; }

    /// <summary>Not written by this item - `26-04`/`26-05`'s own transient-failure path
    /// (`IPushSender`/`PushSendOutcome.TransientFailure`) is the only caller this column is shaped for.
    /// Present now so that work needs no second migration.</summary>
    public DateTimeOffset? LastFailureAt { get; private set; }

    /// <summary>The provider's own short error code, bounded the identical way
    /// <see cref="ChannelDelivery.MaxProviderDetailLength"/> is and for the identical reason: a failure
    /// reason is a code or a phrase, never an essay. Not written by this item - see
    /// <see cref="LastFailureAt"/>'s own remarks.</summary>
    public string? FailureReason { get; private set; }

    private OperatorDevice(
        OperatorDeviceId id, SiteId siteId, OperatorId operatorId, string installationId, PushProvider provider,
        string platform, string token, DateTimeOffset createdAt, DateTimeOffset lastSeenAt, DateTimeOffset? revokedAt)
    {
        Id = id;
        SiteId = siteId;
        OperatorId = operatorId;
        InstallationId = installationId;
        Provider = provider;
        Platform = platform;
        Token = token;
        CreatedAt = createdAt;
        LastSeenAt = lastSeenAt;
        RevokedAt = revokedAt;
    }

    // EF Core materialization only (WebhookEndpoint's own precedent) - never called by domain code.
    private OperatorDevice()
    {
    }

    /// <summary>
    /// The first registration of one app install for one tenancy. `RegisterOperatorDeviceHandler`
    /// calls this only when no row for `(operatorId, installationId)` already exists - every later call
    /// for the same pair is <see cref="Refresh"/>, which is what makes the whole route an idempotent
    /// upsert (`adr/0179` §1) rather than a second insert.
    /// </summary>
    public static OperatorDevice Register(
        OperatorDeviceId id, SiteId siteId, OperatorId operatorId, string installationId, PushProvider provider,
        string platform, string token, DateTimeOffset now)
    {
        ValidateInstallationId(installationId);
        ValidatePlatform(platform);
        ValidateToken(token);
        return new(id, siteId, operatorId, installationId, provider, platform, token, now, lastSeenAt: now, revokedAt: null);
    }

    /// <summary>
    /// Writes a (possibly unchanged) token, touches <see cref="LastSeenAt"/>, and clears
    /// <see cref="RevokedAt"/>/<see cref="LastFailureAt"/>/<see cref="FailureReason"/> - the whole of
    /// what `PUT /api/v1/me/devices/{installationId}` does to an existing row (`adr/0179` §1). Clearing
    /// <see cref="RevokedAt"/> is deliberate, not an oversight: a device that signed out and later signs
    /// back in on the same install is a fresh registration reviving a stale row, not a new one, and
    /// this type's own remarks call that its second real rule ("a revoked device sends nothing until a
    /// fresh registration revives it").
    /// </summary>
    public void Refresh(PushProvider provider, string platform, string token, DateTimeOffset now)
    {
        ValidatePlatform(platform);
        ValidateToken(token);

        Provider = provider;
        Platform = platform;
        Token = token;
        LastSeenAt = now;
        RevokedAt = null;
        LastFailureAt = null;
        FailureReason = null;
    }

    /// <summary>
    /// Idempotent, deliberately unlike <see cref="WebhookEndpoint.Revoke"/> - `adr/0179` states plainly
    /// that both of this type's mutations are idempotent, and a sign-out DELETE, a provider-reported
    /// `UNREGISTERED`, and an operator-removal sweep must each be safe to call twice (at-least-once
    /// delivery, or a double-clicked sign-out button) without surfacing a "you already did that" error
    /// for a caller with no way to have known.
    /// </summary>
    public void Revoke(DateTimeOffset now)
    {
        if (RevokedAt is not null)
        {
            return;
        }

        RevokedAt = now;
    }

    private static void ValidateInstallationId(string installationId)
    {
        if (string.IsNullOrWhiteSpace(installationId))
        {
            throw new ArgumentException("Installation id cannot be empty.", nameof(installationId));
        }

        if (installationId.Length > MaxInstallationIdLength)
        {
            throw new ArgumentException(
                $"Installation id cannot exceed {MaxInstallationIdLength} characters.", nameof(installationId));
        }
    }

    private static void ValidatePlatform(string platform)
    {
        if (string.IsNullOrWhiteSpace(platform))
        {
            throw new ArgumentException("Platform cannot be empty.", nameof(platform));
        }

        if (platform.Length > MaxPlatformLength)
        {
            throw new ArgumentException($"Platform cannot exceed {MaxPlatformLength} characters.", nameof(platform));
        }
    }

    private static void ValidateToken(string token)
    {
        if (string.IsNullOrWhiteSpace(token))
        {
            throw new ArgumentException("Token cannot be empty.", nameof(token));
        }

        if (token.Length > MaxTokenLength)
        {
            throw new ArgumentException($"Token cannot exceed {MaxTokenLength} characters.", nameof(token));
        }
    }
}
