using Ago.Chat.Domain;
using Ago.Platform.Kernel;

namespace Ago.Chat.Application.Abstractions;

/// <summary>
/// `4-05`: the seam between "a send was accepted for processing" and "a send was written to
/// Postgres" - concurrency.md's "In-process pipeline (Api)". Application declares this port because
/// <see cref="Application.UseCases.SendMessage.SendVisitorMessageHandler"/>/<see
/// cref="Application.UseCases.SendMessage.SendOperatorMessageHandler"/> need something they cannot
/// do themselves (queue onto a bounded channel, wait for a background worker's ack) - the same
/// "shape the port around the use case" rule that put <see cref="IConversationRepository"/> here.
/// The implementation (<c>Ago.Chat.Module.Pipeline.ChannelMessagePipeline</c>) is Infrastructure-tier:
/// it owns a <c>System.Threading.Channels.Channel</c>, which Application must never know exists.
/// </summary>
public interface IMessagePipeline
{
    Task<Result<int>> EnqueueAsync(PendingMessage message, CancellationToken cancellationToken);
}

/// <summary>
/// Everything a pipeline worker needs to redo what the handler used to do inline: load the
/// conversation, call the matching <c>AddVisitorMessage</c>/<c>AddOperatorMessage</c>, write the
/// outbox row. Deliberately technology-free (no <c>MessageId</c>/<c>DateTimeOffset</c> - those are
/// generated by the worker at write time, not enqueue time, so a message's id stays roughly
/// time-ordered with when it actually committed rather than when it sat down to wait).
///
/// `5-03`: <see cref="AttachmentId"/> is optional - most messages carry none. When set, the worker
/// (<c>MessageBatchWriter</c>) loads that <see cref="Domain.Attachment"/> in the same transaction and
/// validates it (exists, `Ready`, belongs to this conversation) before the message is allowed to
/// reference it - the same "cheap checks here, real validation in the worker's own transaction" split
/// `SendVisitorMessageHandler`'s own remarks describe for the conversation load.
///
/// `5-07`: <see cref="ClientMessageId"/> is optional for the same reason - forwarded verbatim to
/// <c>Conversation.AddVisitorMessage</c>/<c>AddOperatorMessage</c>, which is where the actual
/// retry-dedup decision happens (see that method's own remarks).
///
/// `7-01`: <see cref="TraceParent"/> is the W3C `traceparent` of the hub method's own manual span
/// (`VisitorHub.SendMessageAsync`/`OperatorHub.SendMessageAsync`), a plain string carried through
/// exactly like <see cref="ClientMessageId"/> - Application never touches
/// <c>System.Diagnostics.Activity</c> itself, only passes this value on to
/// <c>MessageBatchWriter</c>, the pipeline worker that actually starts the DB-write span and tags
/// the outbox row with it (concurrency.md's "In-process pipeline (Api)" already hands the write off
/// through a channel to a different async context, where the hub's own ambient
/// <c>Activity.Current</c> would not otherwise flow - this field is what survives that hop).
/// </summary>
/// `14-06`: <see cref="Content"/> is optional and already validated - the handler turned the
/// caller's raw strings into a <see cref="MessageContent"/> and returned a <c>Result</c> failure if
/// they were malformed, exactly as it already does for <see cref="MessageBody"/>. Nothing downstream
/// of here re-validates it, and nothing anywhere reads inside its payload.
public sealed record PendingMessage(
    ConversationId ConversationId, MessageAuthorKind AuthorKind, Guid AuthorId, MessageBody Body,
    AttachmentId? AttachmentId = null, Guid? ClientMessageId = null, string? TraceParent = null,
    MessageContent? Content = null);
