using Ago.Chat.Domain;
using Ago.Platform.Kernel;

namespace Ago.Chat.Application.Abstractions;

/// <summary>
/// `4-05`: the seam between "a send was accepted for processing" and "a send was written to
/// Postgres" - concurrency.md's "In-process pipeline (Api)". Application declares this port because
/// <see cref="Application.UseCases.SendMessage.SendVisitorMessageHandler"/>/<see
/// cref="Application.UseCases.SendMessage.SendOperatorMessageHandler"/> need something they cannot
/// do themselves (queue onto a bounded channel, wait for a background worker's ack) - the same
/// "shape the port around the use case" rule that put <see cref="IConversationRepository"/> here.
/// The implementation (<c>Ago.Chat.Module.Pipeline.ChannelMessagePipeline</c>) is Infrastructure-tier:
/// it owns a <c>System.Threading.Channels.Channel</c>, which Application must never know exists.
/// </summary>
public interface IMessagePipeline
{
    Task<Result<int>> EnqueueAsync(PendingMessage message, CancellationToken cancellationToken);
}

/// <summary>
/// Everything a pipeline worker needs to redo what the handler used to do inline: load the
/// conversation, call the matching <c>AddVisitorMessage</c>/<c>AddOperatorMessage</c>, write the
/// outbox row. Deliberately technology-free (no <c>MessageId</c>/<c>DateTimeOffset</c> - those are
/// generated by the worker at write time, not enqueue time, so a message's id stays roughly
/// time-ordered with when it actually committed rather than when it sat down to wait).
/// </summary>
public sealed record PendingMessage(ConversationId ConversationId, MessageAuthorKind AuthorKind, Guid AuthorId, MessageBody Body);
