<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup Condition="'$(AgoPlatformDevOverride)' != 'true'">
    <PackageReference Include="Ago.Platform.Hosting" />
  </ItemGroup>

  <ItemGroup Condition="'$(AgoPlatformDevOverride)' == 'true'">
    <ProjectReference Include="..\..\..\ago-platform\src\Ago.Platform.Hosting\Ago.Platform.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ago.Chat.Application\Ago.Chat.Application.csproj" />
    <ProjectReference Include="..\Ago.Chat.Infrastructure.Postgres\Ago.Chat.Infrastructure.Postgres.csproj" />
  </ItemGroup>

</Project>
