// <auto-generated />
using System;
using System.Collections.Generic;
using Ago.Chat.Infrastructure.Postgres.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ago.Chat.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AgoChatDbContext))]
    [Migration("20260829065058_Stage18AddMessageSiteId")]
    partial class Stage18AddMessageSiteId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ago.Chat.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("ThumbnailKey")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_key");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SiteId");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.BillingSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("text")
                        .HasColumnName("payment_method_id");

                    b.Property<int>("RequestedSeats")
                        .HasColumnType("integer")
                        .HasColumnName("requested_seats");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<string>("YooKassaPaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yookassa_payment_id");

                    b.HasKey("Id");

                    b.HasIndex("YooKassaPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_subscriptions_yookassa_payment_id");

                    b.HasIndex("SiteId", "CreatedAt")
                        .HasDatabaseName("ix_billing_subscriptions_site_id_created_at");

                    b.ToTable("billing_subscriptions", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.BillingWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("YooKassaPaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yookassa_payment_id");

                    b.HasKey("Id");

                    b.HasIndex("YooKassaPaymentId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_webhook_events_payment_id_event_type");

                    b.ToTable("billing_webhook_events", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<byte[]>("TokenCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_ciphertext");

                    b.Property<byte[]>("WebhookSecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("webhook_secret_hash");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_credentials_site_kind_active")
                        .HasFilter("active");

                    b.ToTable("channel_credentials", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_address");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_channel_identities_visitor_id");

                    b.HasIndex("SiteId", "Kind", "Address")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_identities_site_kind_address");

                    b.ToTable("channel_identities", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ErasureRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erasure_requested_at");

                    b.Property<bool>("HoldsCapacityClaim")
                        .HasColumnType("boolean")
                        .HasColumnName("holds_capacity_claim");

                    b.Property<int>("LastSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_sequence");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<int>("OperatorLastReadSequence")
                        .HasColumnType("integer")
                        .HasColumnName("operator_last_read_sequence");

                    b.Property<int>("OperatorUnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("operator_unread_count");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.Property<int>("VisitorUnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("visitor_unread_count");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ErasureRequestedAt")
                        .HasDatabaseName("ix_conversations_erasure_pending")
                        .HasFilter("erasure_requested_at is not null");

                    b.HasIndex("OperatorId");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_conversations_waiting")
                        .HasFilter("state = 'Waiting'");

                    b.HasIndex("SiteId", "Id")
                        .HasDatabaseName("ix_conversations_site_all");

                    b.HasIndex("VisitorId", "Id")
                        .HasDatabaseName("ix_conversations_visitor_all");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_kind");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid?>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("_actions")
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<string>("_contentKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_kind");

                    b.Property<string>("_payload")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "ClientMessageId", "CreatedAt")
                        .IsUnique()
                        .HasFilter("client_message_id IS NOT NULL");

                    b.HasIndex("ConversationId", "Sequence", "CreatedAt")
                        .IsUnique();

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("ExternalSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("external_subject_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("active_chats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_chats");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("ExternalSubjectId", "SiteId")
                        .IsUnique()
                        .HasFilter("external_subject_id IS NOT NULL");

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.OperatorInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid?>("RedeemedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_by_operator_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_operator_invites_code_hash");

                    b.HasIndex("RoleId");

                    b.HasIndex("SiteId");

                    b.ToTable("operator_invites", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DemoExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_expires_at");

                    b.Property<DateTimeOffset?>("ErasureRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erasure_requested_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<int>("SeatLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("seat_limit");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("tier");

                    b.PrimitiveCollection<List<string>>("_allowedOrigins")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_origins");

                    b.Property<string>("_locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en")
                        .HasColumnName("widget_locale");

                    b.Property<bool>("_offlineAutoReplyEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("offline_auto_reply_enabled");

                    b.Property<string>("_offlineAutoReplyFallback")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("offline_auto_reply_fallback");

                    b.Property<string>("_offlineAutoReplyRules")
                        .HasColumnType("text")
                        .HasColumnName("offline_auto_reply_rules");

                    b.Property<string>("_widgetPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("bottom-right")
                        .HasColumnName("widget_position");

                    b.Property<string>("_widgetPrimaryColorHex")
                        .HasColumnType("text")
                        .HasColumnName("widget_primary_color_hex");

                    b.HasKey("Id");

                    b.HasIndex("DemoExpiresAt")
                        .HasDatabaseName("ix_sites_demo_expiry")
                        .HasFilter("demo_expires_at is not null");

                    b.HasIndex("ErasureRequestedAt")
                        .HasDatabaseName("ix_sites_erasure_pending")
                        .HasFilter("erasure_requested_at is not null");

                    b.ToTable("sites", null, t =>
                        {
                            t.HasCheckConstraint("ck_sites_widget_locale", "widget_locale IN ('en', 'ru')");

                            t.HasCheckConstraint("ck_sites_widget_position", "widget_position IN ('bottom-right', 'bottom-left')");
                        });
                });

            modelBuilder.Entity("Ago.Chat.Domain.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("visitors", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("ResponseSnippet")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("response_snippet");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId", "Id")
                        .HasDatabaseName("ix_webhook_deliveries_endpoint_id_id");

                    b.HasIndex("EndpointId", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_webhook_deliveries_endpoint_id_message_id");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("SecretCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_ciphertext");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_webhook_endpoints_site_id");

                    b.ToTable("webhook_endpoints", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.ExportRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_export_requests_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("SiteId");

                    b.ToTable("export_requests", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.OperatorRoleRecord", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("OperatorId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("operator_roles", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Ago.Platform.Persistence.Postgres.InboxRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasColumnType("text")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("Ago.Platform.Persistence.Postgres.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("TraceContext")
                        .HasColumnType("text")
                        .HasColumnName("trace_context");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Attachment", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.BillingSubscription", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelCredential", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelIdentity", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Conversation", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Message", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany("_messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Operator", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.OperatorInvite", b =>
                {
                    b.HasOne("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Visitor", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookDelivery", b =>
                {
                    b.HasOne("Ago.Chat.Domain.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookEndpoint", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.ExportRequestEntity", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.OperatorRoleRecord", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Conversation", b =>
                {
                    b.Navigation("_messages");
                });
#pragma warning restore 612, 618
        }
    }
}
