// <auto-generated />
using System;
using System.Collections.Generic;
using Ago.Chat.Infrastructure.Postgres.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ago.Chat.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AgoChatDbContext))]
    [Migration("20260903142106_Stage13RaiseFreeTierSeatLimit")]
    partial class Stage13RaiseFreeTierSeatLimit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ago.Chat.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("ThumbnailKey")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_key");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SiteId");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.BillingSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancel_requested");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset?>("LastRenewalAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_renewal_attempt_at");

                    b.Property<DateTimeOffset?>("PastDueSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("past_due_since");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("text")
                        .HasColumnName("payment_method_id");

                    b.Property<int?>("PendingSeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("pending_seat_count");

                    b.Property<string>("PendingTier")
                        .HasColumnType("text")
                        .HasColumnName("pending_tier");

                    b.Property<int>("RequestedSeats")
                        .HasColumnType("integer")
                        .HasColumnName("requested_seats");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<string>("YooKassaPaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yookassa_payment_id");

                    b.HasKey("Id");

                    b.HasIndex("YooKassaPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_subscriptions_yookassa_payment_id");

                    b.HasIndex("SiteId", "CreatedAt")
                        .HasDatabaseName("ix_billing_subscriptions_site_id_created_at");

                    b.HasIndex("Status", "CurrentPeriodEnd")
                        .HasDatabaseName("ix_billing_subscriptions_status_current_period_end");

                    b.ToTable("billing_subscriptions", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.BillingWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("YooKassaPaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yookassa_payment_id");

                    b.HasKey("Id");

                    b.HasIndex("YooKassaPaymentId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_webhook_events_payment_id_event_type");

                    b.ToTable("billing_webhook_events", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("ProviderAccountId")
                        .HasColumnType("text")
                        .HasColumnName("provider_account_id");

                    b.Property<byte[]>("RefreshTokenCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_ciphertext");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<byte[]>("TokenCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_ciphertext");

                    b.Property<byte[]>("WebhookSecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("webhook_secret_hash");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "ProviderAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_credentials_kind_provideraccountid_active")
                        .HasFilter("active AND provider_account_id IS NOT NULL");

                    b.HasIndex("SiteId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_credentials_site_kind_active")
                        .HasFilter("active");

                    b.ToTable("channel_credentials", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_address");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset?>("UnlinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlinked_at");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_channel_identities_visitor_id");

                    b.HasIndex("SiteId", "Kind", "Address")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_identities_site_kind_address_active")
                        .HasFilter("active");

                    b.ToTable("channel_identities", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ErasureRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erasure_requested_at");

                    b.Property<bool>("HoldsCapacityClaim")
                        .HasColumnType("boolean")
                        .HasColumnName("holds_capacity_claim");

                    b.Property<int>("LastSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_sequence");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<int>("OperatorLastReadSequence")
                        .HasColumnType("integer")
                        .HasColumnName("operator_last_read_sequence");

                    b.Property<int>("OperatorUnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("operator_unread_count");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Unset")
                        .HasColumnName("outcome");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.Property<int>("VisitorUnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("visitor_unread_count");

                    b.Property<string>("_trafficReferrerHost")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("traffic_referrer_host");

                    b.Property<string>("_trafficUtmCampaign")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("traffic_utm_campaign");

                    b.Property<string>("_trafficUtmMedium")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("traffic_utm_medium");

                    b.Property<string>("_trafficUtmSource")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("traffic_utm_source");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ErasureRequestedAt")
                        .HasDatabaseName("ix_conversations_erasure_pending")
                        .HasFilter("erasure_requested_at is not null");

                    b.HasIndex("OperatorId");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_conversations_waiting")
                        .HasFilter("state = 'Waiting'");

                    b.HasIndex("SiteId", "Id")
                        .HasDatabaseName("ix_conversations_site_all");

                    b.HasIndex("VisitorId", "Id")
                        .HasDatabaseName("ix_conversations_visitor_all");

                    b.ToTable("conversations", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversations_outcome", "outcome IN ('Unset', 'Converted', 'NotConverted', 'FollowUpNeeded')");
                        });
                });

            modelBuilder.Entity("Ago.Chat.Domain.ConversationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_conversation_notes_conversation");

                    b.ToTable("conversation_notes", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.EmailThreadState", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("LastInboundMessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_inbound_message_id");

                    b.Property<string>("RootMessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("root_message_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("subject");

                    b.HasKey("ConversationId");

                    b.ToTable("email_threads", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.EnabledModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<string>("EntryPoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_point");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_key");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("TriggerWords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_words");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_enabled_modules_site");

                    b.ToTable("enabled_modules", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_kind");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid?>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retention_class");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("_actions")
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<string>("_contentKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_kind");

                    b.Property<string>("_payload")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "ClientMessageId", "SiteId")
                        .IsUnique()
                        .HasFilter("client_message_id IS NOT NULL");

                    b.HasIndex("ConversationId", "Sequence", "SiteId")
                        .IsUnique();

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.ModuleTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ExternalTaskId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_task_id");

                    b.Property<string>("LastStepKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_step_kind");

                    b.Property<string>("LastStepPayload")
                        .HasColumnType("text")
                        .HasColumnName("last_step_payload");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module_key");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("_lastStepActions")
                        .HasColumnType("text")
                        .HasColumnName("last_step_actions");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("ux_module_tasks_conversation_active")
                        .HasFilter("state = 'Open'");

                    b.ToTable("module_tasks", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.ModuleTaskChannelPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("ChannelIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_identity_id");

                    b.Property<Guid>("ModuleTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_task_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("ChannelIdentityId");

                    b.HasIndex("SiteId");

                    b.HasIndex("VisitorId");

                    b.HasIndex("ModuleTaskId", "ChannelIdentityId")
                        .IsUnique()
                        .HasDatabaseName("ux_module_task_channel_preferences_module_task_channel_identity");

                    b.HasIndex("ModuleTaskId", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ux_module_task_channel_preferences_module_task_priority");

                    b.ToTable("module_task_channel_preferences", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("ExternalSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("external_subject_id");

                    b.Property<bool>("HoldsSeat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("holds_seat");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("active_chats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_chats");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubjectId", "SiteId")
                        .IsUnique()
                        .HasFilter("external_subject_id IS NOT NULL");

                    b.HasIndex("SiteId", "RemovedAt")
                        .HasDatabaseName("ix_operators_site_id_removed_at");

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.OperatorInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_operator_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid?>("RedeemedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_by_operator_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_operator_invites_code_hash");

                    b.HasIndex("RoleId");

                    b.HasIndex("SiteId");

                    b.ToTable("operator_invites", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.PendingChannelLinkRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("RequestedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_operator_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitorId");

                    b.HasIndex("SiteId", "Kind", "CodeHash")
                        .HasDatabaseName("ix_pending_channel_link_requests_site_kind_code_hash");

                    b.ToTable("pending_channel_link_requests", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.PendingPhoneVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("delivery_method");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("VisitorId");

                    b.ToTable("pending_phone_verifications", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DemoExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_expires_at");

                    b.Property<DateTimeOffset?>("ErasureRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erasure_requested_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<int>("SeatLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("seat_limit");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("tier");

                    b.PrimitiveCollection<List<string>>("_allowedOrigins")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_origins");

                    b.Property<string>("_cannedResponses")
                        .HasColumnType("text")
                        .HasColumnName("canned_responses");

                    b.Property<string>("_locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en")
                        .HasColumnName("widget_locale");

                    b.Property<bool>("_offlineAutoReplyEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("offline_auto_reply_enabled");

                    b.Property<string>("_offlineAutoReplyFallback")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("offline_auto_reply_fallback");

                    b.Property<string>("_offlineAutoReplyRules")
                        .HasColumnType("text")
                        .HasColumnName("offline_auto_reply_rules");

                    b.Property<string>("_widgetNoticeText")
                        .HasColumnType("text")
                        .HasColumnName("widget_notice_text");

                    b.Property<string>("_widgetNoticeUrl")
                        .HasColumnType("text")
                        .HasColumnName("widget_notice_url");

                    b.Property<string>("_widgetPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("bottom-right")
                        .HasColumnName("widget_position");

                    b.Property<string>("_widgetPrimaryColorHex")
                        .HasColumnType("text")
                        .HasColumnName("widget_primary_color_hex");

                    b.HasKey("Id");

                    b.HasIndex("DemoExpiresAt")
                        .HasDatabaseName("ix_sites_demo_expiry")
                        .HasFilter("demo_expires_at is not null");

                    b.HasIndex("ErasureRequestedAt")
                        .HasDatabaseName("ix_sites_erasure_pending")
                        .HasFilter("erasure_requested_at is not null");

                    b.ToTable("sites", null, t =>
                        {
                            t.HasCheckConstraint("ck_sites_widget_locale", "widget_locale IN ('en', 'ru')");

                            t.HasCheckConstraint("ck_sites_widget_position", "widget_position IN ('bottom-right', 'bottom-left')");
                        });
                });

            modelBuilder.Entity("Ago.Chat.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_site_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("PreferredChannelIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_channel_identity_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("PreferredChannelIdentityId");

                    b.HasIndex("SiteId");

                    b.ToTable("visitors", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.VisitorContactDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_operator_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitorId", "RecordedAt")
                        .HasDatabaseName("ix_visitor_contact_details_visitor");

                    b.ToTable("visitor_contact_details", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("ResponseSnippet")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("response_snippet");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId", "Id")
                        .HasDatabaseName("ix_webhook_deliveries_endpoint_id_id");

                    b.HasIndex("EndpointId", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_webhook_deliveries_endpoint_id_message_id");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("SecretCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_ciphertext");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_webhook_endpoints_site_id");

                    b.ToTable("webhook_endpoints", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.ConversationTagRecord", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Operator")
                        .HasColumnName("source");

                    b.HasKey("ConversationId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_conversation_tags_tag_id");

                    b.ToTable("conversation_tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversation_tags_source", "source IN ('Operator', 'Ai')");
                        });
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.ExportRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_export_requests_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("SiteId");

                    b.ToTable("export_requests", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.MessageArchiveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retention_class");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "RetentionClass", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ux_message_archives_site_class_period");

                    b.ToTable("message_archives", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.OperatorRoleRecord", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("OperatorId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("operator_roles", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Ago.Platform.Persistence.Postgres.InboxRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasColumnType("text")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("Ago.Platform.Persistence.Postgres.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("TraceContext")
                        .HasColumnType("text")
                        .HasColumnName("trace_context");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Ago.Chat.Domain.Attachment", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.BillingSubscription", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelCredential", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.ChannelIdentity", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Conversation", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.ConversationNote", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.EmailThreadState", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.EnabledModule", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Message", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany("_messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.ModuleTask", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany("_moduleTasks")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.ModuleTaskChannelPreference", b =>
                {
                    b.HasOne("Ago.Chat.Domain.ChannelIdentity", null)
                        .WithMany()
                        .HasForeignKey("ChannelIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.ModuleTask", null)
                        .WithMany()
                        .HasForeignKey("ModuleTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Operator", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.OperatorInvite", b =>
                {
                    b.HasOne("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.PendingChannelLinkRequest", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.PendingPhoneVerification", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Tag", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Visitor", b =>
                {
                    b.HasOne("Ago.Chat.Domain.ChannelIdentity", null)
                        .WithMany()
                        .HasForeignKey("PreferredChannelIdentityId");

                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.VisitorContactDetail", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Visitor", null)
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookDelivery", b =>
                {
                    b.HasOne("Ago.Chat.Domain.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.WebhookEndpoint", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.ConversationTagRecord", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.ExportRequestEntity", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.MessageArchiveEntity", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.OperatorRoleRecord", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Infrastructure.Postgres.Persistence.RoleRecord", b =>
                {
                    b.HasOne("Ago.Chat.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Chat.Domain.Conversation", b =>
                {
                    b.Navigation("_messages");

                    b.Navigation("_moduleTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
